### ISSUE TITLE
unhelpful output if a dependency project has unknown dependencies

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/ropm#22]
I (somehow) accidentally had 

```    
"dependencies": {
        "bsc": "^2.0.0",
        "Log": "file:../../roku-log/roku-log"
    },
```

in my maestro-core package.json

when I try to `ropm install` maestro-view, which includes maestro-core, I get this error message..

I suppose it's valid; but it took me a moment of head-scratching to work it out. .wonder if we could word it better...

up to date, audited 195 packages in 1s
12 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Error: Cannot find suitable program dependency for bsc@2.0.0
    at RopmModule.createPrefixMap (/home/george/.nvm/versions/node/v15.4.0/lib/node_modules/ropm/dist/prefixer/RopmModule.js:176:23)
    at async Promise.all (index 1)
    at async ModuleManager.reduceModulesAndCreatePrefixMaps (/home/george/.nvm/versions/node/v15.4.0/lib/node_modules/ropm/dist/prefixer/ModuleManager.js:69:9)
    at async ModuleManager.process (/home/george/.nvm/versions/node/v15.4.0/lib/node_modules/ropm/dist/prefixer/ModuleManager.js:42:9)
    at async InstallCommand.processModules (/home/george/.nvm/versions/node/v15.4.0/lib/node_modules/ropm/dist/commands/InstallCommand.js:92:9)
    at async InstallCommand.run (/home/george/.nvm/versions/node/v15.4.0/lib/node_modules/ropm/dist/commands/InstallCommand.js:41:9)

**Comment by bogdanterzea** [comment]
I recently started working with ROPM and I get the same console message that @georgejecook mentioned for every package I try to install from [here](https://www.npmjs.com/search?q=ropm). The package is installed and the console displays that message.
Mention: I also have other npm dependencies in my project. Maybe those may affect ROPM but that is just my guess.
![image](https://user-images.githubusercontent.com/49044962/131659161-0f83a4cd-7792-4584-b6b5-4ddc83bec862.png)

**Comment by TwitchBronBron** [comment]
Would you mind sharing your entire package.json file? Also, what OS and nodejs version are you running?

**Comment by bogdanterzea** [comment]
package.json:
```
{
  "name": "xx",
  "version": "1.0.0",
  "devDependencies": {
    "@willowtreeapps/ukor": "^1.1.3",
    "go": "^3.0.1",
    "js-yaml": "^3.13.1",
    "rooibos-cli": "^1.4.0",
    "rooibos-roku": "^4.3.2"
  },
  "license": "UNLICENSED",
  "author": "xx",
  "private": true,
  "ropm": {
    "nonprefix": [
      "roku-data-dog"
    ],
    "rootDir": "src/main/components"
  },
  "dependencies": {
    "roku-data-dog": "^0.10.0"
  }
}
```
npm: '7.20.0'
node: '12.16.2'
OS: Pop!_OS 20.10
Note: On projects with no other dependencies is working just fine to do `ropm install x`
CC: @TwitchBronBron

**Comment by bogdanterzea** [comment]
My problem was fixed by https://github.com/rokucommunity/ropm/pull/49/commits
