### ISSUE TITLE
ropm crashes when installing local npm modules

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/ropm#51]
given pacakge.json containing:

![image](https://user-images.githubusercontent.com/1214545/153000505-76fbee67-8b90-4004-86c9-31eb771e7473.png)

ropm commands, such as copy/install cause a crash:

```> nba-roku@1.12.0 ropm
> ropm copy

ropm: deleting /home/george/hope/nba/nba-roku/src/components/roku_modules
ropm: deleting /home/george/hope/nba/nba-roku/src/source/roku_modules
npm ERR! code ELSPROBLEMS
npm ERR! missing: @swc/core@>=1.2.50, required by ts-node@10.5.0
npm ERR! missing: @swc/wasm@>=1.2.50, required by ts-node@10.5.0
npm ERR! missing: uglify-js@^3.1.4, required by handlebars@4.7.7
npm ERR! missing: encoding@^0.1.0, required by node-fetch@2.6.7
npm ERR! missing: fsevents@~2.3.2, required by chokidar@3.5.3
npm ERR! invalid: colors@1.4.0 /home/george/hope/open-source/maestro/maestro-roku/node_modules/colors
npm ERR! invalid: cors@2.8.5 /home/george/hope/open-source/maestro/maestro-roku/node_modules/cors
npm ERR! invalid: opn@6.0.0 /home/george/hope/open-source/maestro/maestro-roku/node_modules/opn
npm ERR! invalid: proxy-middleware@0.15.0 /home/george/hope/open-source/maestro/maestro-roku/node_modules/proxy-middleware
npm ERR! invalid: send@0.17.2 /home/george/hope/open-source/maestro/maestro-roku/node_modules/send
npm ERR! missing: fsevents@^1.2.7, required by chokidar@2.1.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/george/.npm/_logs/2022-02-08T13_50_39_845Z-debug.log
Error: Failed to compute prod dependencies: Command failed: npm ls --parseable --prod --depth=Infinity
npm ERR! code ELSPROBLEMS
npm ERR! missing: @swc/core@>=1.2.50, required by ts-node@10.5.0
npm ERR! missing: @swc/wasm@>=1.2.50, required by ts-node@10.5.0
npm ERR! missing: uglify-js@^3.1.4, required by handlebars@4.7.7
npm ERR! missing: encoding@^0.1.0, required by node-fetch@2.6.7
npm ERR! missing: fsevents@~2.3.2, required by chokidar@3.5.3
npm ERR! invalid: colors@1.4.0 /home/george/hope/open-source/maestro/maestro-roku/node_modules/colors
npm ERR! invalid: cors@2.8.5 /home/george/hope/open-source/maestro/maestro-roku/node_modules/cors
npm ERR! invalid: opn@6.0.0 /home/george/hope/open-source/maestro/maestro-roku/node_modules/opn
npm ERR! invalid: proxy-middleware@0.15.0 /home/george/hope/open-source/maestro/maestro-roku/node_modules/proxy-middleware
npm ERR! invalid: send@0.17.2 /home/george/hope/open-source/maestro/maestro-roku/node_modules/send
npm ERR! missing: fsevents@^1.2.7, required by chokidar@2.1.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/george/.npm/_logs/2022-02-08T13_50_39_845Z-debug.log

    at InstallCommand.getProdDependencies (/home/george/hope/nba/nba-roku/node_modules/ropm/dist/commands/InstallCommand.js:117:23)
    at InstallCommand.processModules (/home/george/hope/nba/nba-roku/node_modules/ropm/dist/commands/InstallCommand.js:82:34)
    at InstallCommand.run (/home/george/hope/nba/nba-roku/node_modules/ropm/dist/commands/InstallCommand.js:41:20)
    at async CopyCommand.run (/home/george/hope/nba/nba-roku/node_modules/ropm/dist/commands/CopyCommand.js:11:9)
npm ERR! code 1
npm ERR! path /home/george/hope/nba/nba-roku
npm ERR! command failed
npm ERR! command sh -c npm run build-scripts && npm run ropm && npm run build-figma-plugin

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/george/.npm/_logs/2022-02-08T13_50_39_877Z-debug.log

```

this is a real drag for ropm package authors.

**Comment by TwitchBronBron** [comment]
I'm able to reproduce this on my windows machine using a simple test app, so I'll see what I can dig up

**Comment by TwitchBronBron** [comment]
I believe this has been fixed, but I can't remember which release fixed it. Closing for now. If you encounter the issue again, please feel free to re-open.
