### ISSUE TITLE
EINVAL crash on latest nodejs

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/ropm#77]
There's a weird crash with the latest version of NodeJS when running ropm. 
```bash
$ ropm install roku-requests
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:760:9)
    at C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\util.js:24:40
    at new Promise (<anonymous>)
    at Util.spawnAsync (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\util.js:23:16)
    at Util.spawnNpmAsync (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\util.js:37:21)
    at InstallCommand.npmInstall (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\commands\InstallCommand.js:70:27)
    at async InstallCommand.run (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\commands\InstallCommand.js:39:13) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

**Comment by OLSA** [comment]
I get this error while trying to install ropm modules.
The error occurs because recent versions of Node.js (20 and 22) block spawning .cmd files directly for security reasons. This can be resolved by adding `{ shell: true } `to the options passed to child_process.spawn.

In my case, I directly edited the file `node_modules\ropm\dist\util.js` at line 24.
Originally was:

`const child = childProcess.spawn(
  command,
  args !== null && args !== void 0 ? args : [],
  Object.assign(
    Object.assign({}, (options !== null && options !== void 0 ? options : {})),
    { stdio: 'inherit' }
  )
);`

modified it to:

`const child = childProcess.spawn(
  command,
  args !== null && args !== void 0 ? args : [],
  Object.assign(
    Object.assign({}, (options !== null && options !== void 0 ? options : {})),
    { stdio: 'inherit', shell: true }
  )
);`

This change seems to resolve the issue, as the module installation now works correctly.
Regards.

**Comment by addison-adler** [comment]
I am also seeing this error. Has this fix been added to a published version of ropm?

**Comment by addison-adler** [comment]
@OLSA Thank you for your insights! We applied the patch and it's released now in version 0.10.29

**Comment by addison-adler** [comment]
@TwitchBronBron this can be closed, it was fixed in 0.10.29
